# name of the software
name: "Calipso Hub: DVD Rental"
# current version of the software
version: 2.0-SNAPSHOT
# url of the download button
downloadUrl: https://github.com/manosbatsis/calipso-hub-dvdrental
# licence of the software
license: GNU AGPLv3
licenseUrl: https://opensource.org/licenses/AGPL-3.0

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/manosbatsis/calipso-hub-dvdrental

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/manosbatsis/calipso-hub-dvdrental
  - title: Issues
    url: https://github.com/manosbatsis/calipso-hub-dvdrental/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: manosbatsis
  repo: calipso-hub-dvdrental

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap